---
- name: Converge
  hosts: all
  gather_facts: true

  # play-level roles
  roles: []
 
  tasks:
  -
    name: "Consul"
    include_role:
      name: ansible-role-hashistack-install
    vars:
      app_name: consul
      app_version: '1.12.2'
      manage_service: true
      cni_install: true
      app_config:
        datacenter: dc1
        data_dir: /var/opt/consul
        server: true
        bootstrap_expect: 1
        client_addr: '0.0.0.0'
        ui_config:
          enabled: true
        performance:
          raft_multiplier: 8
        ports:
          grpc: 8502
        connect:
          enabled: true
  