#"docker exec -e COLUMNS={columns} -e LINES={lines} -e TERM=bash -e TERM=xterm -ti {instance} bash"
---
driver:
  name: docker
  options:
    login_cmd_template: docker exec -ti {instance} bash
    ansible_connection_options:
      ansible_connection: docker

platforms:
- name: mlc-vault-docker
  image: ubuntu:jammy
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  capabilities:
  - SYS_ADMIN
  - CAP_IPC_LOCK
  memory: 512M
  cpus: 1
  privileged: false
  exposed_ports:
  - "8200/tcp" # Consul API/UI
  published_ports:
  - "0.0.0.0:8200:8200/tcp"

scenario:
  create_sequence:
  - dependency
  - create
  converge_sequence:
  - dependency
  - create
  - converge
  destroy_sequence:
  - destroy

dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
    requirements-file: molecule/resources/requirements.yml

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
