-
  name: create application config folder
  become: true
  ansible.builtin.file:
    path: "{{ folder_config }}/{{ app_name }}.d"
    state: directory
    mode: 0750
    group: "{{ app_user }}"
    owner: "{{ app_user }}"
-
  name: create application data folder
  become: true
  ansible.builtin.file:
    path: "{{ folder_data }}/{{ app_name }}"
    state: directory
    mode: 0750
    group: "{{ app_user }}"
    owner: "{{ app_user }}"
-
  name: render application config file
  become: true
  ansible.builtin.copy:
    content: "{{ app_config | to_nice_json }}"
    dest: "{{ folder_config }}/{{ app_name }}.d/{{ manage_config_file }}.json"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0644
  when: app_config.keys() | length > 0
