 -
  ansible.builtin.copy:
    content: "{{ config | to_nice_json }}"
    dest: "{{ config_folder }}/{{ app }}.d/{{ app }}.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  when: config.keys() | length > 0
  become: true