 -
  ansible.builtin.copy:
    content: "{{ app_config | to_nice_json }}"
    dest: "{{ folder_config }}/{{ app_name }}.d/{{ app_name }}.json"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0644
  when: app_config.keys() | length > 0
  become: true