-
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/{{ app }}/{{ version }}/{{ app }}_{{ version }}_linux_amd64.zip"
    dest: /opt/{{ app }}/{{ app }}.zip
    checksum: "sha256:https://releases.hashicorp.com/{{ app }}/{{ version }}/{{ app }}_{{ version }}_SHA256SUMS"
  register: archive_downloaded
  become: true
-
  ansible.builtin.stat:
    path: "{{ archive_downloaded.dest }}"
    checksum_algorithm: sha256
    get_checksum: yes
  register: archive_status
  become: true
-
  ansible.builtin.stat:
    path: "{{ bin_folder }}/{{ app }}"
  register: bin_status
  become: true
-
  ansible.builtin.unarchive:
    src: "{{ archive_downloaded.dest }}"
    dest: "{{ bin_folder }}"
    remote_src: yes
    mode: 0755
    owner: root
    group: root
  notify: restart_service
  when: |
    force_install or
    archive_downloaded.changed or
    not bin_status.stat.exists
  become: true