-
  ansible.builtin.apt:
    update_cache: yes
    #cache_valid_time: 300
  changed_when: no
  become: true
-
  ansible.builtin.apt:
    pkg:
    - gnupg
    - unzip
    - curl
    state: present
  become: true
