-
  become: true
  ansible.builtin.file:
    path: "/opt/{{ app_name }}"
    state: directory
    mode: 0750
    group: "{{ app_user }}"
    owner: "{{ app_user }}"
-
  become: true
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/{{ app_name }}/{{ app_version }}/{{ app_name }}_{{ app_version }}_linux_amd64.zip"
    dest: /opt/{{ app_name }}/{{ app_name }}.zip
    checksum: "sha256:https://releases.hashicorp.com/{{ app_name }}/{{ app_version }}/{{ app_name }}_{{ app_version }}_SHA256SUMS"
    mode: '0644'
    timeout: 300
  register: archive_downloaded
  until: archive_downloaded is succeeded
-
  become: true
  ansible.builtin.stat:
    path: "{{ archive_downloaded.dest }}"
    checksum_algorithm: sha256
    get_checksum: yes
  register: archive_status
-
  become: true
  ansible.builtin.stat:
    path: "{{ folder_binary }}/{{ app_name }}"
  register: bin_status
-
  become: true
  ansible.builtin.unarchive:
    src: "{{ archive_downloaded.dest }}"
    dest: "{{ folder_binary }}"
    remote_src: yes
    mode: 0755
    owner: root
    group: root
  notify: restart_service
  when: |
    app_force_install or
    archive_downloaded.changed or
    not bin_status.stat.exists
