- # RENDER SERVICE TEMPLATE
  ansible.builtin.template:
    src: "{{ app_name }}.service.j2"
    dest: "{{ folder_service }}/{{ app_name }}.service"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 644
  when: manage_service
  become: true