# TASKS
---
-
  name: ASSERT
  include_tasks: _assert.yml
-
  name: INFO
  ansible.builtin.debug:
    msg: "Application: {{ hashistack.name | upper }}"
  when: true
-
  name: OS | initialize
  include_tasks: "_{{ ansible_os_family | lower }}.yml"
  when: |
    (ansible_os_family | lower) in ["debian"]
-
  name: HASHISTACK | User tasks
  include_tasks: _hashistack_user.yml
  when: true
-
  name: HASHISTACK | Installation tasks
  include_tasks: _hashistack_install.yml
  when: hashistack.version is defined
-
  name: HASHISTACK | Service tasks
  include_tasks: _hashistack_services.yml
  when: hashistack.service is defined
-
  name: HASHISTACK | Configuration tasks
  include_tasks: _hashistack_config.yml
  when: hashistack.config is defined
-
  name: EXTRAS | CNI plugins
  include_tasks: _extras_cni.yml
  when: hashistack.cni_version is defined
-
  name: FINALIZE | Flush handlers
  ansible.builtin.meta: flush_handlers
