- name: assert
  include_tasks: "_assert.yml"

- debug:
    msg: "Installing {{ app_name | default('N/A',true) | upper }} (v{{ app_version | default('N/A',true) }})"
  when: true

- name: Initialize
  include_tasks: "_install_{{ ansible_os_family | lower }}.yml"

- name: Create folders
  include_tasks: _folders.yml

- name: Install HashiCorp binary
  include_tasks: _install_hashistack.yml
  when:
  - manage_binary

- name: Install CNI binaries
  include_tasks: _install_extra_cni.yml
  when: cni_install

- name: Create services
  include_tasks: _services.yml

- name: Create config
  include_tasks: _config.yml

- ansible.builtin.meta: flush_handlers
