- name: assert
  include_tasks: "_assert.yml"

- debug:
    msg: "Application: {{ app_name | default('N/A',true) | upper }} (v{{ app_version | default('N/A',true) }})"
  when: true

- name: Initialize
  include_tasks: "_install_{{ ansible_os_family | lower }}.yml"

- name: Manage Binary
  include_tasks: _install_hashistack.yml
  when: manage_binary

- name: Manage Service
  include_tasks: _services.yml
  when: manage_service

- name: Manage COnfiguration
  include_tasks: _config.yml
  when: manage_config

- name: Extra - CNI-plugins
  include_tasks: _install_extra_cni.yml
  when: cni_install

- ansible.builtin.meta: flush_handlers
