-
  name: assert
  include_tasks: "_assert.yml"
-
  name: print role info
  ansible.builtin.debug:
    msg: "Application: {{ app_name | default('N/A',true) | upper }}"
  when: true
-
  name: initialize os
  include_tasks: "_install_{{ ansible_os_family | lower }}.yml"
-
  name: include binary tasks
  include_tasks: _install_hashistack.yml
  when: manage_binary
-
  name: include service tasks
  include_tasks: _services.yml
  when: manage_service
-
  name: include configuration tasks
  include_tasks: _config.yml
  when: manage_config
-
  name: include extra tasks - cni plugins
  include_tasks: _install_extra_cni.yml
  when: cni_install
-
  name: flush handlers
  ansible.builtin.meta: flush_handlers
