---
- name: Converge
  hosts: all
  gather_facts: true

  # play-level roles
  roles: []
 
  tasks:
  - name: "Nomad Installation"
    include_role:
      name: ansible-role-hashistack-install
    vars:
      app_name: nomad
      app_version: '1.3.1'
      manage_service: true
  
  - name: "Nomad Configuration"
    include_role:
      name: ansible-role-hashistack-install
    vars:
      app_name: nomad
      manage_binary: false
      manage_config: true
      app_config:
        datacenter: dc1
        data_dir: /var/opt/nomad
        server:
          enabled: true
          bootstrap_expect: 1
        client:
          enabled: false
        plugin:
          raw_exec:
            config:
              enabled: true
