---
- name: Converge
  hosts: all
  gather_facts: true

  # play-level roles
  roles: []
 
  tasks:
  - name: "Nomad Installation"
    include_role:
      name: ansible-role-hashistack-install
    vars:
      hashistack:
        name: nomad
        version: '1.3.1'
        service: true
  
  - name: "Nomad Configfiles"
    include_role:
      name: ansible-role-hashistack-install
    vars:
      filename_config: "{{ item.file }}"
      hashistack:
        name: nomad
        config: "{{ item.content }}"
    loop:
    - file: server
      content:
        datacenter: dc1
        data_dir: /var/opt/nomad
        server:
          enabled: true
          bootstrap_expect: 1
    - file: client
      content:
        client:
          enabled: false
        plugin:
          raw_exec:
            config:
              enabled: true
  
  - ansible.builtin.shell:
      cmd: nohup /usr/local/bin/nomad agent -config /etc/opt/nomad.d &
    when: false
