---
- name: Converge
  hosts: all
  #become: true
  gather_facts: true

  # play-level roles
  roles: []
 
  tasks:
  - # task level roles (dynamic)
    name: Terraform
    include_role:
      name: ansible-role-hashistack-install
    vars:
      hashistack:
        name: terraform
        version: '1.2.2'
    tags: terraform
    when: true
  -
    name: Consul template
    include_role:
      name: ansible-role-hashistack-install
    vars:
      hashistack:
        name: consul-template
        version: '0.29.0'
    tags: consul-template
    when: true
  -
    name: Consul
    include_role:
      name: ansible-role-hashistack-install
    vars:
      hashistack_user: consul
      hashistack_group: consul
      hashistack:
        name: consul
        version: '1.12.2'
        service: true
        cni_version: '1.1.1'
        config:
          datacenter: dc1
          data_dir: /var/opt/consul
          server: true
          bootstrap_expect: 1
          client_addr: '0.0.0.0'
          ui_config:
            enabled: true
          performance:
            raft_multiplier: 8
          ports:
            grpc: 8502
          connect:
            enabled: true
    tags: consul
    when: true
  -
    name: Nomad
    include_role:
      name: ansible-role-hashistack-install
    vars:
      hashistack:
        name: nomad
        version: '1.3.1'
    tags: nomad
    when: true
