---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  #- name: nomad
  #  version: '1.3.1'
  #- name: vault
  #  version: '1.10.3'
  #- name: boundary
  #  version: '0.8.1'
  #- name: waypoint
  #  version: '0.8.2'
  #- name: packer
  #  version: '1.8.0'
  
  # play-level roles
  roles:
  #- role:
  #    name: ansible-role-hashistack-install
  #  vars:
  #    app: "{{ item.app }}"
  #    version: "{{ item.version }}"
 
  tasks:
  # task level role (dynamic)
  
  - name: "Terraform"
    include_role:
      name: ansible-role-hashistack-install
    vars:
      app: terraform
      version: '1.2.1'
  
  - name: "Consul Server"
    include_role:
      name: ansible-role-hashistack-install
    vars:
      app: consul
      version: '1.12.1'
      create_service: true
      config:
        datacenter: "dc1"
        data_dir: /var/opt/consul
        server: true
        bootstrap_expect: 1
