---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  
  vars:
    apps:
    -
      name: terraform
      version: '1.2.1'
    -
      name: consul
      version: '1.12.1'
      create_service: true
      config:
        datacenter: "dc1"
        data_dir: /var/opt/consul
        server: true
        bootstrap_expect: 1
    #- name: nomad
    #  version: '1.3.1'
    #- name: vault
    #  version: '1.10.3'
    #- name: boundary
    #  version: '0.8.1'
    #- name: waypoint
    #  version: '0.8.2'
    #- name: packer
    #  version: '1.8.0'
  
  tasks:

  - name: "HashiStack Installation"
    include_role:
      name: ansible-role-hashistack-install
    vars:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      config: "{{ item.config | default({},true) }}"
      create_service: "{{ item.create_service | default(false,true) }}"
    loop: "{{ apps }}"

