---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
    requirements-file: molecule/default/requirements.yml

provisioner:
  name: ansible

verifier:
  name: ansible

lint: |
  set -e
  yamllint .

driver:
  name: docker
  options: #"docker exec -e COLUMNS={columns} -e LINES={lines} -e TERM=bash -e TERM=xterm -ti {instance} bash"
    login_cmd_template: "docker exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: docker

platforms:
- name: mlc-ubuntu-docker
  image: ubuntu:jammy
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  capabilities:
  - SYS_ADMIN
  memory: 512M
  cpus: 1
  #privileged: true
  #pre_build_image true

scenario:
  create_sequence:
  - dependency
  - create
  converge_sequence:
  - dependency
  - create
  - converge
  destroy_sequence:
  - destroy
